CREATE TABLE user(
 user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
 uid VARCHAR(20) UNIQUE NOT NULL,
 upw VARCHAR(100) NOT NULL,
 nm VARCHAR(20) NOT NULL,
 pic VARCHAR(50),
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);

SELECT * FROM USER;

-- FEED 글 내용, 작성자, 작성일시, 위치(text)
-- 사진은 정규화를 위반하기 때문에 제외
CREATE TABLE feed(
 feed_id BIGINT AUTO_INCREMENT PRIMARY KEY,
 writer_id BIGINT NOT NULL,
 contents VARCHAR(1000),
 location VARCHAR(30),
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);

-- PK, 사진 저장위치, feed_id
CREATE TABLE feed_pics(
  feed_pic_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  feed_id BIGINT NOT NULL,
  pic VARCHAR(30) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- fk는 추후에 추가